import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

import "@stream-io/video-react-sdk/dist/css/styles.css";
import "react-datepicker/dist/react-datepicker.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vicalls - Meeting App",
  description: "Generated by create next app",
  openGraph: {
    title: "Vicalls - Meeting App",
    description: "Published by Advie.R",
    url: "https://vicalls.vercel.app",
    siteName: "Vicalls",
    images: [
      {
        url: "https://vicalls.vercel.app/images/icon512_rounded.png",
        width: 1260,
        height: 800,
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Vicalls - Meeting App",
    description: "Published by Advie.R",
    site: "@advie_r",
    images: ["https://vicalls.vercel.app/images/ss.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`${inter.className} bg-dark-2`}>
        <ClerkProvider>
          <main>
            {children}
            <Toaster />
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
